classifieds/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from realty.views import get_city

from . import views

urlpatterns = [
    url(r'^good-deals/$', views.SearchView.as_view(), name='good_deals'),
    url(r'^pets/$', views.SearchView.as_view(), name='pets'),
    url(r'^sports-and-leisure/$', views.SearchView.as_view(), name='sports_and_leisure'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^search-ajax/', views.ElasticSearchAjax.as_view(), name='search-ajax'),
    url(r'^details/(?P<pk>\d+)/$', views.DetailClassifiedView.as_view(), name='details'),
    url(r'^add/', views.AddClassifiedView.as_view(), name="add-classified"),
    url(r'^get_city/', get_city, name='get_city'),
    url(r'^edit/(?P<pk>\d+)/$', views.EditClassifiedView.as_view(), name='edit'),
]

jobs/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^search/', views.SearchView.as_view(), name="search"),
    url(r'^search-ajax/', views.ElasticSearchAjax.as_view(), name='search-ajax'),
    url(r'^details/(?P<pk>\d+)/$', views.DetailJobView.as_view(), name='details'),
    url(r'^add/', views.AddJobView.as_view(), name="add-job"),
    url(r'^get_city/', views.get_city, name='get_city'),
    url(r'^get_employer/', views.get_employer, name='get_employer'),
    url(r'^edit/(?P<pk>\d+)/$', views.EditJobView.as_view(), name='edit'),
]

luxdjango/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.views.i18n import javascript_catalog

from geoip.views import GetLocationByIPView
from vehicles.views import HomeView, ImageAsyncUpload

js_info_dict = {
    'packages': ('luxdjango.static.assets.base.js.modules',)
}

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog'),
    url(r'^rosetta/', include('rosetta.urls')),

    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% raw %}{% url 'admin:index' %}{% endraw %}
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("luxdjango.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^vehicles/', include('vehicles.urls', namespace="vehicles")),
    url(r'^realty/', include('realty.urls', namespace="realty")),
    url(r'^jobs/', include('jobs.urls', namespace="jobs")),

    url(r'^get-location-by-ip/', GetLocationByIPView.as_view()),

    url(r'^classifieds/', include('classifieds.urls', namespace="classifieds")),
    url(r'^image-upload/$', ImageAsyncUpload.as_view(), name="image_async_upload"),

    url(r'^search/', include('overall_search.urls', namespace="overallsearch")),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    # urlpatterns += staticfiles_urlpatterns()
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

luxdjango/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^subscribe-on-search/$', view=views.Subscribe.as_view(), name='subscribe_user'),
    url(r'^social_login_redirect/', view=views.social_redirect, name='social_login_redirect'),
    url(r'^delete-subscriptions/$', view=views.DeleteSubscriptions.as_view()),
    url(r'^delete-posts/$', view=views.DeletePosts.as_view()),
    url(r'^hide-phones/$', view=views.HidePhones.as_view()),
    url(r'^update-post/$', view=views.UpdatePost.as_view()),
    url(r'^adtoken/(?P<token>\w{10,})/(?P<action>.+)/$', view=views.TokenAuth.as_view(), name='adtoken'),
    url(r"^confirm-email/(?P<email>.+)/$", views.EmailVerificationSent.as_view(), name="email_verification_sent"),
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    # URL pattern for the UserDetailView
    url(
        regex=r'^account/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^subscriptions/$',
        view=views.UserSubscriptionsView.as_view(),
        name='subscriptions'
    ),
    url(
        regex=r'^posts/$',
        view=views.UserPostsView.as_view(),
        name='posts'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(r'check/$', views.CheckView.as_view()),
]

classifieds/views.py
# -*- coding: utf-8 -*-
from django.views.generic import ListView, TemplateView, DetailView, View
from django_ajax.mixin import AJAXMixin
from collections import OrderedDict, defaultdict
from realty.models import City
from django.core.urlresolvers import reverse
from vehicles.models import Country
from vehicles.views import CALLING_CODE
from .models import Classified, Category, SubCategory, SubSubCategory, ClassifiedImage
import copy, urllib
import simplejson as json
from .form import ClassifiedForm

from django.http import HttpResponseRedirect
from luxdjango.utils import handnle_form_images, get_tmp_image_urls, get_user_data, post_to_facebook
from django.http.response import HttpResponse
from django.shortcuts import render
from geoip.utils import get_location_by_ip
from allauth.account.models import EmailAddress
from haystack.query import SearchQuerySet
from haystack.utils.geo import Point, D

from luxdjango.users.form import UserForm
from luxdjango.users.models import User, Token
from luxdjango.users.utils2 import send_notification_after_adding_post
from realty.form import max_images




class SearchView(TemplateView):
    template_name = 'classifieds/search.html'

    def get_context_data(self):
        context = super(SearchView, self).get_context_data()
        context['list_of_country'] = Country.objects.all()
        return context



class GoodDealsView(SearchView):
    pass

class PetsView(SearchView):
    pass

class SprortsvView(SearchView):
    pass


class DetailClassifiedView(DetailView):
    model = Classified

    def get(self, context, pk):
        if self.request.is_ajax():
            data = get_user_data(Classified, pk)
            return HttpResponse(data)
        else:
            return super(DetailClassifiedView, self).get(context, pk)


class ElasticSearchAjax(AJAXMixin, TemplateView):
    FACET = OrderedDict([
        ('sub_category_index', (SubCategory, 'name')),
        ('sub_sub_category_index', (SubSubCategory, 'name')),
        ('country_index', None),
    ])

    RANGE_FILTER = [
        'price_index',
    ]

    def queryset(self):
        q = SearchQuerySet()
        if 'good-deals' in self.request.META['HTTP_REFERER']:
            q = q.filter(big_category=u'gooddeals')
        elif 'pets' in self.request.META['HTTP_REFERER']:
            q = q.filter(big_category='pets')
        elif 'sports-and-leisure' in self.request.META['HTTP_REFERER']:
            q = q.filter(big_category='sports')

        r = self.request.GET

        if r.get('q'):
            q = q.filter(text=r.get('q'))

        for p in r:
            if p in self.FACET:
                params = {p: r.get(p)}
                q = q.filter(**params)

        for p in r:
            if p in self.RANGE_FILTER:
                y = r.get(p).split(',')
                params = {p + '__range': [int(y[0].replace('.', '')), int(y[1].replace('.', ''))]}
                q = q.filter(**params)
        if r.get('category_index'):
            q = q.filter(category_index=r['category_index'])

        if r.get('city'):
            q = q.filter(city_index=r['city'])
        if r.get('countries'):
            country_ids = str(r['countries']).split(',')
            q = q.filter(country_index__in=country_ids)
            self.cities = City.objects.filter(country_id__in=country_ids)
        else:
            self.cities = City.objects.all()

        distance = r.get('distance')
        if distance and distance != '1000.00':
            distance = D(km=int(r.get('distance').replace('.00', '')))

            if 'location' in self.request.COOKIES:
                location = json.loads(urllib.unquote(self.request.COOKIES['location']))
                latitude = location['coords']['lat']
                longitude = location['coords']['lng']
            # else:
            #     location = get_location_by_ip(self.request)
            #     latitude = location.location.latitude
            #     longitude = location.location.longitude
            if location:
                user_point = Point(float(longitude), float(latitude))
                q = q.dwithin('location_index', user_point, distance)

        sort = r.get('sort')
        if sort:
            q = q.order_by(sort)
        else:
            q = q.order_by('-date_index')
        return q

    def faceted(self, search_result):
        fin_counts = OrderedDict()
        for f in self.FACET:
            search_result = search_result.facet(f)
        counts = search_result.facet_counts().get('fields', {})
        for f in self.FACET:
            if f in counts:
                if self.FACET[f]:
                    name_dict = {int(index): None for index, count in counts[f]}
                    names = self.FACET[f][0].objects.filter(
                        pk__in=name_dict.keys()
                    ).only('id', self.FACET[f][1])
                    for i in names:
                        name_dict[i.id] = getattr(i, self.FACET[f][1])
                    result = [
                        {'index': index, 'count': count, 'name': name_dict[int(index)]}
                        for index, count in counts[f]
                        ]
                    fin_counts.update({f: sorted(result, key=lambda k: k['name'])})
                else:
                    fin_counts.update(
                        {f: [{'index': index, 'count': count, 'name': index} for index, count in counts[f]]}
                    )
        return fin_counts

    def check_boxes_filters(self, facets):
        check_boxes_filters = copy.deepcopy(facets)
        if 'country_index' in check_boxes_filters:
            del check_boxes_filters["country_index"]
        return check_boxes_filters

    def get(self, request, *args, **kwargs):
        search_result = self.queryset()
        facets = self.faceted(search_result)

        if request.GET.get('show'):
            post_count = int(request.GET['show'])
        else:
            post_count = 10
        template = ''
        if request.GET.get('style') and request.GET.get('style') == 'grid':
            template = 'classifieds/grid_item_preview.html'
            post_count = 32
        else:
            template = 'classifieds/item_preview.html'
        search_list_result = lambda: render(
            request,
            template,
            {'query': True, 'object_list': search_result, 'post_count': post_count}
        )

        left_sidebar_filters = lambda: render(
            request,
            'search/left_sidebar_filters.html',
            {
                'facets': self.check_boxes_filters(facets),
                'conditions': request.GET,
                'cities': self.cities,
                'selected_city': int(request.GET.get('city', 0)),
            }
        )
        if not request.GET.get('scroll'):
            AJAX_TEMPLATE = {'inner-fragments': {
                '#search-list-result': search_list_result(),
                '#left-sidebar-filters': left_sidebar_filters(),
            }}
        else:
            AJAX_TEMPLATE = {'append-fragments': {'#search-list-result': search_list_result()}}

        return AJAX_TEMPLATE


class AddClassifiedView(TemplateView):
    template_name = 'classifieds/add_classified.html'
    classified_form = ClassifiedForm()

    def get(self, request, *args, **kwargs):
        classified_form = ClassifiedForm()
        user_form = UserForm() if not request.user.is_authenticated() else None
        return render(request, self.template_name,
                      {"form": classified_form,
                       'header': 'classified',
                       'images_tmp': get_tmp_image_urls(request.META['CSRF_COOKIE']),
                       'user_form': user_form,
                       'calling_code': json.dumps(CALLING_CODE),
                       'categories': get_options()})

    def post(self, request):
        classified_form = ClassifiedForm(data=request.POST)
        user_form = UserForm(data=request.POST) if not request.user.is_authenticated() else None
        if classified_form.is_valid() and (
                    request.user.is_authenticated() or user_form.is_valid()):
            return self.form_valid(request, classified_form, user_form)
        return render(request, self.template_name, {
            "form": classified_form,
            'header': 'classified',
            'images_tmp': get_tmp_image_urls(request.META['CSRF_COOKIE']),
            'user_form': user_form,
            'calling_code': json.dumps(CALLING_CODE),
            'categories': get_options()})

    def form_valid(self, request, classified_form, user_form):
        city_name = classified_form.cleaned_data.get('city')
        if request.user.is_anonymous():
            user = User.objects.get_or_create(email=user_form.cleaned_data.get('email'),
                                              defaults={
                                                  'phones': request.POST.getlist('phones'),
                                              })[0]
            EmailAddress.objects.get_or_create(email=user.email, defaults={'user_id': user.id})
            classified_form.email = user.email
        else:
            user = request.user
            classified_form.email = request.user.email
        if 'hide_phones' in request.POST:
            if not user.hide_phones:
                user.hide_phones = True
                user.save()
        else:
            if user.hide_phones:
                user.hide_phones = False
                user.save()
        user_verified = user.is_verified()
        city = City.objects.get_or_create(name=city_name, country=classified_form.cleaned_data.get('country'))
        classified = classified_form.save(commit=False)
        classified.city = city[0]
        classified.phones = request.POST.getlist('phones')
        classified.author = user
        if not user.is_authenticated() or not user_verified:
            classified.is_active = False
        classified.save()

luxdjango/templates/classifieds/grid_item_preview.html
{% load pagination_tags staticfiles thumbnail %}
{% autopaginate object_list post_count %}
{% load staticfiles i18n %}
{% for result in object_list %}
    {% with i=result.object %}
        {% if i.is_active == True %}
            <div class="col-md-3 col-sm-6 c-margin-b-20">
                <div class="c-content-product-2 c-bg-white c-border">
                    <div class="c-content-overlay">
                        <div class="c-overlay-wrapper">
                            <div class="c-overlay-content">
                                <a class="btn btn-md c-btn-grey-1 c-btn-uppercase c-btn-bold c-btn-border-1x c-btn-square"
                                   href="{{ i.get_absolute_url }}">{% trans 'Explore' %}</a>
                            </div>
                        </div>
                        {% thumbnail i.images.first.image "260x230" crop="center" as im %}
                            <div class="c-bg-img-center c-overlay-object" data-height="height"
                                 style="height: 230px; background-image: url({{ im.url }});"></div>
                            {% empty %}
                            <div class="c-bg-img-center c-overlay-object" data-height="height"
                                 style="height: 230px; background-image: url({% static 'assets/base/img/nopic.png' %});"></div>
                        {% endthumbnail %}
                    </div>
                    <div class="c-info">
                        <p class="c-title c-font-16 c-font-slim">
                            <a class="c-theme-link" href="{{ i.get_absolute_url }}"
                               title="{{ i.title }}">
                                {% if i.title|length > 24 %}
                                    {{ i.title|slice:'21' }}...
                                {% else %}
                                    {{ i.title }}
                                {% endif %}
                            </a>
                        </p>
                        <p class="c-title c-font-16 c-font-slim">

                        </p>
                        {% if i.price %}
                            <p class="c-price c-font-16 c-slim-thin">{{ i.price }} &#8364;
                                {% if i.price_history and i.price > i.price_history|last %}
                                    <span class="c-font-26 c-font-line-through c-font-red">{{ i.price_history|last }} &#8364;</span>
                                {% endif %}
                            </p>
                        {% else %}
                            <p class="c-price c-font-16 c-slim-thin">
                                <br>
                            </p>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endif %}
    {% endwith %}
    {% empty %}<p>{% trans 'No results found' %}.</p>{% endfor %}
{#{% paginate %}#}

luxdjango/templates/classifieds/item_preview.html
{% load pagination_tags staticfiles i18n thumbnail %}
{% autopaginate object_list post_count %}
{% for result in object_list %}
    {% with i=result.object %}
    {% if i.is_active %}
        <div class="row c-margin-b-40">
            <div class="c-content-product-2 c-bg-white">
                <div class="col-md-4">
                    <div class="c-content-overlay">
                        <div class="c-overlay-wrapper">
                            <div class="c-overlay-content">
                                <a class="btn btn-md c-btn-grey-1 c-btn-uppercase c-btn-bold c-btn-border-1x c-btn-square"
                                   href="{{ i.get_absolute_url }}">{% trans 'Explore' %}</a>
                            </div>
                        </div>
                        {% thumbnail i.images.first.image "260x230" crop="center" as im %}
                            <div class="c-bg-img-center c-overlay-object" data-height="height"
                                 style="height: 230px; background-image: url({{ im.url }});"></div>
                        {% empty %}
                            <div class="c-bg-img-center c-overlay-object" data-height="height"
                                 style="height: 230px; background-image: url({% static 'assets/base/img/nopic.png'%});"></div>
                        {% endthumbnail %}
                    </div>
                </div>
                <div class="col-md-8">
                    <div class="c-info-list">
                        <h3 class="c-title c-font-bold c-font-22 c-font-dark">
                            <a class="c-theme-link" href="{% url "classifieds:details" i.id %}">
                                {% if i.title %}
                                    {{ i.title }}
                                {% endif %}
                            </a>
                        </h3>
                        <p class="c-desc c-font-16 c-font-thin">
                            {{ i.country.name }} {% if i.city_id %}, {{ i.city.name }} {% endif %}
                        </p>
                        {% if i.price %}
                            <p class="c-price c-font-26 c-font-thin">{{ i.price }} &#8364;
                                {% if i.price_history and i.price > i.price_history|last %}
                                    <span class="c-font-26 c-font-line-through c-font-red">&#8364;{{ i.price_history|last }}</span>
                                {% endif %}
                            </p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
    {% endwith %}
    {% empty %}<p>No results found.</p>{% endfor %}
{#{% paginate %}#}

luxdjango/templates/classifieds/search.html
{% extends "search/search_wrapper.html" %}
{% load staticfiles i18n %}
{% block sort %}
    <div class="c-filter" id="sort">
        <label class="control-label c-font-16">{% trans 'Sort&nbsp;By' %}:</label>
        <select id="sort" class="form-control c-square c-theme c-input">
            <option selected value="-date_index">{% trans "Date" %} ({% trans "New" %} &gt; {% trans "Old" %})</option>
            <option value="date_index">{% trans "Date" %} ({% trans "Old" %} &gt; {% trans "New" %})</option>
            <option value="price_index">{% trans "Price" %} ({% trans "Low" %} &gt; {% trans "High" %})</option>
            <option value="-price_index">{% trans "Price" %} ({% trans "High" %} &gt; {% trans "Low" %})</option>
        </select>
    </div>
{% endblock sort %}

{% block sidebar_range_filters %}
    <div class="c-padding-20 c-margin-t-30 c-bg-grey-1 c-bg-img-bottom-right">
        <div class="c-content-title-1">
            <h3 class="c-font-uppercase c-font-bold">{% trans "Price" %}</h3>
            <div class="c-line-left"></div>
            <div id="price_index-range_slider" ></div>
            <input class="input-number" id="price_index-input-number-r">
            <input class="input-number" id="price_index-input-number-l">
        </div>
    </div>
{% endblock sidebar_range_filters %}

{% block extra_js %}
    {{ block.super }}
    <script>
        window.djangoContext.urls.ajaxSearch = "{% url 'classifieds:search-ajax' %}";
        document.addEventListener('DOMContentLoaded', function () {
            SearchPage({
                q_text: "{{ request.GET.q }}",
                rangeFiltersList: {
                    'price_index': {
                        'range': {
                            'min': [0],
                            '5%': [50, 50],
                            '15%': [300, 100],
                            '25%': [1000, 500],
                            '50%': [15000, 1000],
                            '55%': [20000, 5000],
                            '60%': [50000, 10000],
                            '70%': [100000, 50000],
                            '80%': [500000, 100000],
                            '90%': [1000000, 500000],
                            'max': [2000000]
                        }
                    }
                }
            })
        })
    </script>
{% endblock extra_js %}