classifieds/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from realty.views import get_city

from . import views

urlpatterns = [
    url(r'^good-deals/$', views.SearchView.as_view(), name='good_deals'),
    url(r'^pets/$', views.SearchView.as_view(), name='pets'),
    url(r'^sports-and-leisure/$', views.SearchView.as_view(), name='sports_and_leisure'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^search-ajax/', views.ElasticSearchAjax.as_view(), name='search-ajax'),
    url(r'^details/(?P<pk>\d+)/$', views.DetailClassifiedView.as_view(), name='details'),
    url(r'^add/', views.AddClassifiedView.as_view(), name="add-classified"),
    url(r'^get_city/', get_city, name='get_city'),
    url(r'^edit/(?P<pk>\d+)/$', views.EditClassifiedView.as_view(), name='edit'),
]

jobs/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^search/', views.SearchView.as_view(), name="search"),
    url(r'^search-ajax/', views.ElasticSearchAjax.as_view(), name='search-ajax'),
    url(r'^details/(?P<pk>\d+)/$', views.DetailJobView.as_view(), name='details'),
    url(r'^add/', views.AddJobView.as_view(), name="add-job"),
    url(r'^get_city/', views.get_city, name='get_city'),
    url(r'^get_employer/', views.get_employer, name='get_employer'),
    url(r'^edit/(?P<pk>\d+)/$', views.EditJobView.as_view(), name='edit'),
]

luxdjango/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.views.i18n import javascript_catalog

from geoip.views import GetLocationByIPView
from vehicles.views import HomeView, ImageAsyncUpload

js_info_dict = {
    'packages': ('luxdjango.static.assets.base.js.modules',)
}

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog'),
    url(r'^rosetta/', include('rosetta.urls')),

    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% raw %}{% url 'admin:index' %}{% endraw %}
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("luxdjango.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^vehicles/', include('vehicles.urls', namespace="vehicles")),
    url(r'^realty/', include('realty.urls', namespace="realty")),
    url(r'^jobs/', include('jobs.urls', namespace="jobs")),

    url(r'^get-location-by-ip/', GetLocationByIPView.as_view()),

    url(r'^classifieds/', include('classifieds.urls', namespace="classifieds")),
    url(r'^image-upload/$', ImageAsyncUpload.as_view(), name="image_async_upload"),

    url(r'^search/', include('overall_search.urls', namespace="overallsearch")),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    # urlpatterns += staticfiles_urlpatterns()
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

luxdjango/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^subscribe-on-search/$', view=views.Subscribe.as_view(), name='subscribe_user'),
    url(r'^social_login_redirect/', view=views.social_redirect, name='social_login_redirect'),
    url(r'^delete-subscriptions/$', view=views.DeleteSubscriptions.as_view()),
    url(r'^delete-posts/$', view=views.DeletePosts.as_view()),
    url(r'^hide-phones/$', view=views.HidePhones.as_view()),
    url(r'^update-post/$', view=views.UpdatePost.as_view()),
    url(r'^adtoken/(?P<token>\w{10,})/(?P<action>.+)/$', view=views.TokenAuth.as_view(), name='adtoken'),
    url(r"^confirm-email/(?P<email>.+)/$", views.EmailVerificationSent.as_view(), name="email_verification_sent"),
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    # URL pattern for the UserDetailView
    url(
        regex=r'^account/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^subscriptions/$',
        view=views.UserSubscriptionsView.as_view(),
        name='subscriptions'
    ),
    url(
        regex=r'^posts/$',
        view=views.UserPostsView.as_view(),
        name='posts'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(r'check/$', views.CheckView.as_view()),
]

realty/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^get_city/', views.get_city, name='get_city'),
    url(r'^details/(?P<pk>\d+)/$', views.DetailRealtyView.as_view(), name='details'),
    url(r'^edit/(?P<pk>\d+)/$', views.EditRealtyView.as_view(), name='edit'),
    url(r'^add/', views.AddRealtyView.as_view(), name="add-realty"),
    url(r'^search/', views.SearchView.as_view(), name='search'),
    url(r'^search-ajax/', views.ElasticSearchAjax.as_view(), name='search-ajax'),
    url(r'^delete-image/$', view=views.DeleteImage.as_view()),
    url(r'^map/$', view=views.MapView.as_view(), name='map'),
    url(r'^map/ajax/$', view=views.MapAjaxView.as_view(), name='map_ajax'),
]

vehicles/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.VehicleView.as_view(), name="all_vehicles"),
    url(r'^all-vehicles-ajax/$', views.AllVehiclesElasticSearchAjax.as_view(), name="all_vehicles_ajax"),
    url(r'^add_car', views.AddCarView.as_view(), name="add-car"),
    url(r'^add_motorbike', views.AddCarView.as_view(), name="add-moto"),
    # url(r'^cars/search/', views.MainCarView.as_view(), name="car_search"),
    # url(r'^motorbikes/search/', views.MainCarView.as_view(), name="moto_search"),
    url(r'^car/details/(?P<pk>[0-9]+)/$', views.DetailCarView.as_view(), name='car-details'),
    url(r'^motorbike/details/(?P<pk>[0-9]+)/$', views.DetailMotoView.as_view(), name='moto-details'),
    url(r'^search-ajax/', views.ElasticSearchAjax.as_view(), name='search-ajax'),
    url(r'^search/autocomplete/', views.autocomplete, name='autocomplete'),
    url(r'^postadd/$', views.AddCarView.as_view(), name="AddCar"),
    url(r'^get_models/', views.get_models, name='get_models'),
    url(r'^get_colors/', views.get_colors, name='get_colors'),
    url(r'^get_brands/', views.get_brands, name='get_brands'),
    url(r'^get_city/', views.get_city, name='get_city'),
    url(r'^car/edit/(?P<pk>\d+)/$', views.EditVehicleView.as_view(), name='edit-car'),
    url(r'^motorbike/edit/(?P<pk>\d+)/$', views.EditVehicleView.as_view(), name='edit-moto'),
    url(r'^delete-image/$', view=views.DeleteImage.as_view()),
]

luxdjango/users/models.py
import uuid
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.postgres.fields import ArrayField
from django.core.validators import RegexValidator
from django.db import models
from django.utils import timezone
from django.utils.translation import ugettext as _

from classifieds.models import Classified
from jobs.models import Job
from luxdjango.users.managers import UserManager
from realty.models import Realty
from vehicles.models import Country, Car, Moto


class User(AbstractBaseUser):
    email = models.EmailField(verbose_name='email address', max_length=255, unique=True)
    is_active = models.BooleanField(default=True)
    hide_phones = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    user_country = models.ForeignKey(Country, verbose_name=_("User country"), null=True)
    location_json = models.CharField(max_length=500, null=True, blank=True)
    phones = ArrayField(
        models.CharField(max_length=24, validators=[
            RegexValidator(r'^[\s\+0-9]{6,17}$', 'Enter a valid phone number.')
        ]),
        null=True, blank=True
    )

    objects = UserManager()
    USERNAME_FIELD = 'email'

    def get_full_name(self):
        # The user is identified by their email address
        return self.email

    def get_short_name(self):
        # The user is identified by their email address
        return self.email

    def __unicode__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin

    def is_verified(self):
        return (self.socialaccount_set.all().exists()
                or self.emailaddress_set.filter(email=self.email, verified=True).exists())

    @property
    def location(self):
        if self.location_json:
            return json.loads(self.location_json)
        else:
            return None


class Token(models.Model):
    user = models.ForeignKey(User)
    token = models.CharField(max_length=40, primary_key=True)
    created = models.DateTimeField(default=timezone.now)
    car = models.ForeignKey(Car, blank=True, null=True)
    moto = models.ForeignKey(Moto, blank=True, null=True)
    realty = models.ForeignKey(Realty, blank=True, null=True)
    job = models.ForeignKey(Job, blank=True, null=True)
    classified = models.ForeignKey(Classified, blank=True, null=True)

    def save(self, *args, **kwargs):
        if not self.token:
            self.token = self.generate_token()
        return super(Token, self).save(*args, **kwargs)

    def generate_token(self):
        return uuid.uuid4().hex

    def __unicode__(self):
        return self.token


CATEGORY_CHOICES = ((1, 'vehicles'), (2, 'realty'), (3, 'jobs'))


class Subscription(models.Model):
    category = models.PositiveIntegerField(choices=CATEGORY_CHOICES, blank=False, default=1)
    token = models.ForeignKey(Token, blank=True, null=True)
    user = models.ForeignKey(User)
    filters = models.CharField(max_length=500)
    last_notification = models.DateTimeField(null=True, blank=True)
    category = models.PositiveIntegerField(choices=CATEGORY_CHOICES)
    location_json = models.CharField(max_length=500, null=True, blank=True)

    @property
    def location(self):
        if self.location_json:
            return json.loads(self.location_json)
        else:
            return None


class TrustedCountry(models.Model):
    country = models.ForeignKey(Country)

luxdjango/templates/headers/base_header.html
{% load i18n staticfiles     %}
<!-- BEGIN: LAYOUT/HEADERS/HEADER-2 -->
<!-- BEGIN: HEADER 2 -->
<header class="c-layout-header c-layout-header-6 c-navbar-fluid" data-minimize-offset="80">
    <div class="c-topbar">
        <div class="container" style="position:relative">
            <div class="col-xs-4">
                <a href="/" class="c-logo">
                    <img src="{% static "assets/base/img/skruut.jpg" %}" alt="JANGO" class="c-desktop-logo">
{#                    <img src="{% static "assets/base/img/skruut.jpg" %}" alt="JANGO" class="c-desktop-logo-inverse">#}
{#                    <img src="{% static "assets/base/img/skruut.jpg" %}" alt="JANGO" class="c-mobile-logo">#}
                </a>
            </div>
            <nav class="c-top-menu col-xs-offfset-8">
                <ul class="c-links c-theme-ul">
                    <li class="c-cart-toggler-wrapper">
                        <a href="#"
                           class="c-font-uppercase c-font-bold c-btn-icon c-cart-toggler">
                            {% trans "categories" %} <span class="caret"></span>
                        </a>
                    </li>

                    <div class="c-cart-menu">
                        <div class="c-cart-menu-items">
                            <div class="c-content-tab-1 c-theme c-margin-t-30">
                                <div class="clearfix">
                                    <ul class="nav nav-tabs c-font-uppercase c-font-bold">
                                        {% for item in header_categories %}
                                            <li {% if item.active %}class="active"{% endif %}>
                                                <a href="#tab_1_{{ forloop.counter }}_content"
                                                   data-toggle="tab">{{ item.big_cat }}</a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                                <div class="tab-content c-bordered c-padding-lg">
                                    {% for item in header_categories %}
                                        <div class="tab-pane {% if item.active %}active{% endif %}"
                                             id="tab_1_{{ forloop.counter }}_content">
                                            <div class="row">
                                                {% for sub_cat_list in item.cats %}
                                                    <div class="col-md-4">
                                                        <ul class="c-content-list-1 c-theme c-separator-dot">
                                                            {% for cat in sub_cat_list %}
                                                                <li><a href="{{ cat.url }}">{{ cat.name | capfirst }}</a></li>
                                                            {% endfor %}
                                                        </ul>
                                                    </div>
                                                {% endfor %}
                                            </div>
                                        </div>
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>

                    <li class="c-divider"></li>
                    {% if request.user.is_authenticated %}
                        <li><a href="{% url "users:detail" %}" class="c-font-uppercase c-font-bold">{% trans "My profile" %}</a></li>
                    {% endif %}
                    <li>
                        <a id="add_post" class="c-font-uppercase c-font-bold c-font-dark"
                           data-toggle="modal" data-target="#choose-category">
                            <span class="glyphicon glyphicon-plus"></span> {% trans "Post Add" %}
                        </a>
                    </li>
                    <li>
                        {% if request.user.is_authenticated %}
                            <a id="sign-out" href="{% url "account_logout" %}" data-toggle="modal" data-target="#login-form"
                               class="btn c-btn-square c-btn-uppercase c-btn-bold">{% trans 'Sign out' %}</a>
                        {% else %}
                            <a id="sign-in" href="javascript:;" data-toggle="modal" data-target="#login-form"
                               class="btn c-theme-btn c-btn-square c-btn-uppercase c-btn-bold">{% trans 'Sign In' %}</a>
                        {% endif %}
                    </li>
                </ul>
                <form id="lang-form" class="hidden" action="{% url 'set_language' %}" method="post">
                    {% csrf_token %}
                    <input type="text" name="language">
                </form>
                {% get_current_language as LANGUAGE_CODE %}
                {% get_available_languages as LANGUAGES %}
                {% get_language_info_list for LANGUAGES as languages %}
                <ul class="c-ext c-theme-ul">
                    <li class="c-lang dropdown c-last">
                        <a id="current-lang" href="#">{{ LANGUAGE_CODE }}</a>
                        <ul class="dropdown-menu pull-right" role="menu">
                            {% for language in languages %}
                                {% if language.code != LANGUAGE_CODE %}
                                    <li class="change-lang" data-lang-code={{ language.code }}>
                                        <a href="#">{{ language.name_local }}</a>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>
    <div class="c-navbar">
        <div class="container">
            <div class="c-navbar-wrapper clearfix">
                <form class="c-quick-search" action="#" name="search_form">
                    <input type="text" name="q" placeholder="{% trans "Type to search" %}" value=""
                           class="form-control fire-reload" autocomplete="off">
                    <div class="list-group" id="search-counts">
                      <a href="{% url 'vehicles:all_vehicles' %}"data-key="vehicles"
                         class="list-group-item">{% trans "Vehicles" %} <span class="badge"></span></a>
                      <a href="{% url 'realty:search' %}"data-key="realty"
                         class="list-group-item">{% trans "Realty" %} <span class="badge"></span></a>
                      <a href="{% url 'jobs:search' %}"data-key="jobs"
                         class="list-group-item">{% trans "Jobs" %} <span class="badge"></span></a>
                      <a href="{% url 'classifieds:good_deals' %}"data-key="gooddeals"
                         class="list-group-item">{% trans "Good deals" %} <span class="badge"></span></a>
                      <a href="{% url 'classifieds:sports_and_leisure' %}"data-key="sports"
                         class="list-group-item">{% trans "Sport and lasure" %} <span class="badge"></span></a>
                      <a href="{% url 'classifieds:pets' %}"data-key="pets"
                         class="list-group-item">{% trans "Pets" %} <span class="badge"></span></a>
                      <a href="#" data-key="notfound"
                         class="list-group-item">{% trans "No results found" %} <span class="badge"></span></a>
                    </div>
                </form>
                <div id="search-filters-toggler">
                    <span class="toggler-line"></span>
                    <span class="toggler-line"></span>
                    <span class="toggler-line"></span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- END: HEADER 2 -->
<!-- END: LAYOUT/HEADERS/HEADER-2 -->

<!-- BEGIN: CONTENT/USER/FORGET-PASSWORD-FORM -->
<div class="modal fade c-content-login-form" id="forget-password-form" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content c-square">
            <div class="modal-header c-no-border">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h3 class="c-font-24 c-font-sbold">{% trans "Password Recovery" %}</h3>
                <p>{% trans "To recover your password please fill in your email address" %}</p>
                <form>
                    <div class="form-group">
                        <label for="forget-email" class="hide">{% trans "Email" %}</label>
                        <input type="email" class="form-control input-lg c-square" id="forget-email"
                               placeholder="Email"></div>
                    <div class="form-group">
                        <button class="btn c-theme-btn btn-md c-btn-uppercase c-btn-bold c-btn-square c-btn-login"
                                type="submit">{% trans "Submit" %}</button>
                        <a href="javascript:;" class="c-btn-forgot" data-toggle="modal" data-target="#login-form"
                           data-dismiss="modal">{% trans "Back To Login" %}</a>
                    </div>
                </form>
            </div>
            <div class="modal-footer c-no-border">
                <span class="c-text-account">{% trans "Don't Have An Account Yet ?" %}</span>
                <a class="btn c-btn-dark-1 btn c-btn-uppercase c-btn-bold c-btn-slim c-btn-border-2x c-btn-square c-btn-signup"
                   href="javascript:;" data-toggle="modal" data-target="#signup-form"
                   data-dismiss="modal">{% trans "Signup" %}!</a>

            </div>
        </div>
    </div>
</div>
<!-- END: CONTENT/USER/FORGET-PASSWORD-FORM -->

{% include "account/modal_signup.html" %}
{% include "account/modal_login.html" %}
{% include "account/modal_login_or_enter_email.html" %}

<div class="modal fade" id="choose-category" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel">
    <div class="modal-dialog modal-sm" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel"><span class="glyphicon glyphicon-plus"></span>{% trans 'POST ADD' %}</h4>
            </div>
            <div class="modal-body">
                <div>
                    <a href="{% url 'vehicles:add-car' %}"
                       class="btn btn-block c-theme-btn c-btn-square c-btn-uppercase c-btn-bold">{% trans 'ADD CAR' %}</a>
                    <br>
                    <a href="{% url 'vehicles:add-moto' %}"
                       class="btn btn-block c-theme-btn c-btn-square c-btn-uppercase c-btn-bold">{% trans 'ADD MOTORBIKE' %}</a>
                    <br>
                    <a href="{% url 'realty:add-realty' %}"
                       class="btn btn-block c-theme-btn c-btn-square c-btn-uppercase c-btn-bold">{% trans 'ADD REALTY' %}</a>
                    <br>
                    <a href="{% url 'jobs:add-job' %}"
                       class="btn btn-block c-theme-btn c-btn-square c-btn-uppercase c-btn-bold">{% trans 'ADD JOB' %}</a>
                    <br>
                    <a href="{% url 'classifieds:add-classified' %}"
                       class="btn btn-block c-theme-btn c-btn-square c-btn-uppercase c-btn-bold">{% trans 'ADD CLASSIFIED' %}</a>
                </div>
            </div>
            <div class="modal-footer">
                <button class="btn c-theme-btn c-btn-square c-btn-uppercase c-btn-bold"
                        type="button" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

luxdjango/templates/headers/base_header2.html
{% load staticfiles %}
<header class="c-layout-header c-layout-header-4 c-layout-header-default-mobile" data-minimize-offset="80">
    <div class="c-navbar">
        <div class="container">
            <div class="c-navbar-wrapper clearfix">
                <!-- BEGIN: BRAND -->
                <div class="c-brand c-pull-left" style="margin:20px 10px">
                    <a href="/" class="c-logo" style="font-weight:bold; color:#7a7a7a; font-size: 30px; display:inline-block">
                        <img src="{% static 'assets/base/img/skruut60.jpg' %}" alt="JANGO" class="c-desktop-logo">
                        <img src="{% static 'assets/base/img/skruut40.jpg' %}" alt="JANGO" class="c-desktop-logo-inverse">
                        <img src="{% static 'assets/base/img/skruut40.jpg' %}" alt="JANGO" class="c-mobile-logo">
                        <span>SKRUUT</span>
                    </a>
                    <button class="c-hor-nav-toggler" type="button" data-target=".c-mega-menu">
                        <span class="c-line"></span>
                        <span class="c-line"></span>
                        <span class="c-line"></span>
                    </button>
                    <button class="c-search-toggler" type="button">
                        <i class="fa fa-search"></i>
                    </button>
                </div>
                <!-- END: BRAND -->
                <!-- BEGIN: QUICK SEARCH -->
                <form class="c-quick-search" action="#">
                    <input type="text" name="query" placeholder="Type to search..." value="" class="form-control" autocomplete="off">
                    <span class="c-theme-link">&times;</span>
                </form>
                <!-- END: QUICK SEARCH -->
                <!-- BEGIN: HOR NAV -->
                <!-- BEGIN: MEGA MENU -->
                <!-- Dropdown menu toggle on mobile: c-toggler class can be applied to the link arrow or link itself depending on toggle mode -->
                <nav class="c-mega-menu c-pull-right c-mega-menu-dark c-mega-menu-dark-mobile c-fonts-uppercase c-fonts-bold">
                    <ul class="nav navbar-nav c-theme-nav">
                        <li><a href="{% url 'vehicles:search' %}" class="c-link">vehicles</a></li>
                        <li class="c-active c-menu-type-classic"><a href="{% url 'realty:search' %}" class="c-link">realty</a></li>
                        <li class="c-search-toggler-wrapper">
                            <a href="#" class="c-btn-icon c-search-toggler">
                                <i class="fa fa-search"></i>
                            </a>
                        </li>
                        <li>
                            <a href="javascript:;" data-toggle="modal" data-target="#login-form"
                                class="c-btn-border-opacity-04 c-btn btn-no-focus c-btn-header btn btn-sm c-btn-border-1x c-btn-dark c-btn-circle c-btn-uppercase c-btn-sbold">
                                <i class="icon-user"></i> Sign In</a>
                        </li>
                    </ul>
                </nav>
                <!-- END: MEGA MENU -->
                <!-- END: HOR NAV -->
            </div>
        </div>
    </div>
</header>