classifieds/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from realty.views import get_city

from . import views

urlpatterns = [
    url(r'^good-deals/$', views.SearchView.as_view(), name='good_deals'),
    url(r'^pets/$', views.SearchView.as_view(), name='pets'),
    url(r'^sports-and-leisure/$', views.SearchView.as_view(), name='sports_and_leisure'),
    url(r'^search/$', views.SearchView.as_view(), name='search'),
    url(r'^search-ajax/', views.ElasticSearchAjax.as_view(), name='search-ajax'),
    url(r'^details/(?P<pk>\d+)/$', views.DetailClassifiedView.as_view(), name='details'),
    url(r'^add/', views.AddClassifiedView.as_view(), name="add-classified"),
    url(r'^get_city/', get_city, name='get_city'),
    url(r'^edit/(?P<pk>\d+)/$', views.EditClassifiedView.as_view(), name='edit'),
]

jobs/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^search/', views.SearchView.as_view(), name="search"),
    url(r'^search-ajax/', views.ElasticSearchAjax.as_view(), name='search-ajax'),
    url(r'^details/(?P<pk>\d+)/$', views.DetailJobView.as_view(), name='details'),
    url(r'^add/', views.AddJobView.as_view(), name="add-job"),
    url(r'^get_city/', views.get_city, name='get_city'),
    url(r'^get_employer/', views.get_employer, name='get_employer'),
    url(r'^edit/(?P<pk>\d+)/$', views.EditJobView.as_view(), name='edit'),
]

luxdjango/urls.py
# -*- coding: utf-8 -*-
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView
from django.views.i18n import javascript_catalog

from geoip.views import GetLocationByIPView
from vehicles.views import HomeView, ImageAsyncUpload

js_info_dict = {
    'packages': ('luxdjango.static.assets.base.js.modules',)
}

urlpatterns = [
    url(r'^$', HomeView.as_view(), name="home"),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^jsi18n/$', javascript_catalog, js_info_dict, name='javascript-catalog'),
    url(r'^rosetta/', include('rosetta.urls')),

    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% raw %}{% url 'admin:index' %}{% endraw %}
    url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),

    # User management
    url(r'^users/', include("luxdjango.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    url(r'^vehicles/', include('vehicles.urls', namespace="vehicles")),
    url(r'^realty/', include('realty.urls', namespace="realty")),
    url(r'^jobs/', include('jobs.urls', namespace="jobs")),

    url(r'^get-location-by-ip/', GetLocationByIPView.as_view()),

    url(r'^classifieds/', include('classifieds.urls', namespace="classifieds")),
    url(r'^image-upload/$', ImageAsyncUpload.as_view(), name="image_async_upload"),

    url(r'^search/', include('overall_search.urls', namespace="overallsearch")),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# from django.contrib.staticfiles.urls import staticfiles_urlpatterns
if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    # urlpatterns += staticfiles_urlpatterns()
    # urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permission Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

luxdjango/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^subscribe-on-search/$', view=views.Subscribe.as_view(), name='subscribe_user'),
    url(r'^social_login_redirect/', view=views.social_redirect, name='social_login_redirect'),
    url(r'^delete-subscriptions/$', view=views.DeleteSubscriptions.as_view()),
    url(r'^delete-posts/$', view=views.DeletePosts.as_view()),
    url(r'^hide-phones/$', view=views.HidePhones.as_view()),
    url(r'^update-post/$', view=views.UpdatePost.as_view()),
    url(r'^adtoken/(?P<token>\w{10,})/(?P<action>.+)/$', view=views.TokenAuth.as_view(), name='adtoken'),
    url(r"^confirm-email/(?P<email>.+)/$", views.EmailVerificationSent.as_view(), name="email_verification_sent"),
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    # URL pattern for the UserDetailView
    url(
        regex=r'^account/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^subscriptions/$',
        view=views.UserSubscriptionsView.as_view(),
        name='subscriptions'
    ),
    url(
        regex=r'^posts/$',
        view=views.UserPostsView.as_view(),
        name='posts'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(r'check/$', views.CheckView.as_view()),
]

overall_search/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^ajax/$', views.ElasticSearchAjax.as_view(), name="search_ajax"),
]

vehicles/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.VehicleView.as_view(), name="all_vehicles"),
    url(r'^all-vehicles-ajax/$', views.AllVehiclesElasticSearchAjax.as_view(), name="all_vehicles_ajax"),
    url(r'^add_car', views.AddCarView.as_view(), name="add-car"),
    url(r'^add_motorbike', views.AddCarView.as_view(), name="add-moto"),
    # url(r'^cars/search/', views.MainCarView.as_view(), name="car_search"),
    # url(r'^motorbikes/search/', views.MainCarView.as_view(), name="moto_search"),
    url(r'^car/details/(?P<pk>[0-9]+)/$', views.DetailCarView.as_view(), name='car-details'),
    url(r'^motorbike/details/(?P<pk>[0-9]+)/$', views.DetailMotoView.as_view(), name='moto-details'),
    url(r'^search-ajax/', views.ElasticSearchAjax.as_view(), name='search-ajax'),
    url(r'^search/autocomplete/', views.autocomplete, name='autocomplete'),
    url(r'^postadd/$', views.AddCarView.as_view(), name="AddCar"),
    url(r'^get_models/', views.get_models, name='get_models'),
    url(r'^get_colors/', views.get_colors, name='get_colors'),
    url(r'^get_brands/', views.get_brands, name='get_brands'),
    url(r'^get_city/', views.get_city, name='get_city'),
    url(r'^car/edit/(?P<pk>\d+)/$', views.EditVehicleView.as_view(), name='edit-car'),
    url(r'^motorbike/edit/(?P<pk>\d+)/$', views.EditVehicleView.as_view(), name='edit-moto'),
    url(r'^delete-image/$', view=views.DeleteImage.as_view()),
]

luxdjango/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals
import json, re
import datetime
from django.utils import timezone
from django.contrib.auth import login
from django.core.urlresolvers import resolve
from django.conf import settings
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.utils.translation import ugettext as _
from django.shortcuts import redirect
from allauth.account.models import EmailAddress
from django.views.generic import ListView, RedirectView, UpdateView, View

from braces.views import LoginRequiredMixin
from django.views.generic import TemplateView

from classifieds.models import Classified, SubCategory, SubSubCategory
from jobs.models import Job, WorkHours, Contract
from jobs.models import Category as JobCategory
from classifieds.models import Category as ClassifiedsCategory
from .models import User, Subscription, Token
from vehicles.models import Country, Car, Brand, Model, Moto
from realty.models import PropertyType, PropertyTypeType, City, Realty

MODELS = {'cars': Car, 'realties': Realty, 'moto': Moto, 'classifieds': Classified, 'jobs': Job}
MODELS_FOR_EMAIL = {
    'car': 'vehicles:edit-car',
    'moto': 'vehicles:edit-moto',
    'job': 'jobs:edit',
    'classified': 'classifieds:edit',
    'realty': 'realty:edit'
}


class UserDetailView(LoginRequiredMixin, TemplateView):
    template_name = 'users/user_detail.html'
    model = User
    slug_field = "email"
    slug_url_kwarg = "email"


class UserPostsView(LoginRequiredMixin, TemplateView):
    template_name = 'users/user_posts.html'
    model = User
    # These next two lines tell the view to index lookups by email
    slug_field = "email"
    slug_url_kwarg = "email"

    def get_context_data(self, **kwargs):
        context = super(UserPostsView, self).get_context_data(**kwargs)
        delta = timezone.now() - datetime.timedelta(days=30)
        context['validate'] = {}
        for name, model in MODELS.iteritems():
            context[name] = model.objects.filter(author=self.request.user.id, update_date__gt=delta)
        for name, model in MODELS.iteritems():
            objects = model.objects.filter(author=self.request.user.id, update_date__lt=delta)
            if objects:
                context['validate'][name] = objects
        return context


class UserSubscriptionsView(LoginRequiredMixin, TemplateView):
    template_name = 'users/user_subscriptions.html'
    model = User
    # These next two lines tell the view to index lookups by email
    slug_field = "email"
    slug_url_kwarg = "email"

    def get_context_data(self, **kwargs):
        context = super(UserSubscriptionsView, self).get_context_data(**kwargs)
        subscriptions = self.request.user.subscription_set.all()
        jobs = {}
        realties = {}
        cars = {}
        moto = {}
        classifieds = {}

        for s in subscriptions:
            raw_filters = json.loads(s.filters)
            filters = {}
            if 'brand_index' in raw_filters:
                raw_filters['brand_index'] = Brand.objects.get(pk=raw_filters['brand_index']).brand_name
            if 'model_index' in raw_filters:
                raw_filters['model_index'] = Model.objects.get(pk=raw_filters['model_index']).model_name
            if 'work_hours_index' in raw_filters:
                raw_filters['work_hours_index'] = WorkHours.objects.get(pk=raw_filters['work_hours_index']).work_hours
            if 'category_index' in raw_filters:
                if s.category == 3:
                    raw_filters['category_index'] = JobCategory.objects.get(pk=raw_filters['category_index']).name
                else:
                    raw_filters['category_index'] = ClassifiedsCategory.objects.get(
                        pk=raw_filters['category_index']).name
            if 'contract_index' in raw_filters:
                raw_filters['contract_index'] = Contract.objects.get(pk=raw_filters['contract_index']).contract
            if 'sub_category_index' in raw_filters:
                raw_filters['sub_category_index'] = SubCategory.objects.get(pk=raw_filters['sub_category_index']).name
            if 'sub_sub_category_index' in raw_filters:
                raw_filters['sub_sub_category_index'] = SubSubCategory.objects.get(
                    pk=raw_filters['sub_sub_category_index']).name
            if 'property_type_type' in raw_filters:
                filters['Property type'] = PropertyTypeType.objects.filter(
                    id=raw_filters['property_type_type']
                ).first().name
            elif 'property_type' in raw_filters:
                filters['Property type'] = PropertyType.objects.filter(
                    id=raw_filters['property_type']
                ).first().name
            if 'city' in raw_filters:
                filters['City'] = City.objects.get(id=raw_filters['city'])
            if 'deal' in raw_filters:
                filters[_('Deal')] = _('Sale') if raw_filters['deal'] == 1 else _('Rent')

            for key in raw_filters:
                key2 = None
                if key.endswith('_index'):
                    key2 = key.replace('_index', '')
                elif key == 'q' and raw_filters[key]:
                    key2 = 'text'
                elif key == 'countries' and raw_filters[key]:
                    key2 = key
                    country_ids = [int(x) for x in str(raw_filters[key]).split(',')]
                    country_names = Country.objects.filter(
                        id__in=country_ids
                    ).values_list('name', flat=True)
                    raw_filters[key] = ', '.join(country_names)
                elif key == 'distance':
                    # user location should be in user model to filter search by distance
                    continue
                elif key in ['price_index', 'year_index', 'mileage_index', 'year_index', 'category', 'title']:
                    key2 = key
                    raw_filters[key] = raw_filters[key].replace(',', ' - ')
                if key2:
                    key2 = key2.replace('_', ' ').capitalize()
                    filters[key2] = raw_filters[key]
                    if key2 not in ['Brand', 'Countries']:
                        filters[key2] = filters[key2].lower()
            if not filters:
                filters['Without filters'] = 'any updates'
            if s.category == 3:
                jobs[s.id] = filters
            elif s.category == 2:
                realties[s.id] = filters
            elif s.category == 4:
                classifieds[s.id] = filters
            elif s.category == 5:
                moto[s.id] = filters
            else:
                cars[s.id] = filters

        context['subscriptions'] = []
        if cars:
            context['subscriptions'].append((cars, _('cars')))
        if moto:
            context['subscriptions'].append((moto, _('motorbikes')))
        if realties:
            context['subscriptions'].append((realties, _('realties')))
        if jobs:
            context['subscriptions'].append((jobs, _('jobs')))
        if classifieds:
            context['subscriptions'].append((classifieds, _('classifieds')))
        return context


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail")


class TokenAuth(TemplateView):
    template_name = 'users/user_detail.html'
    msg = ''

    def get(self, request, token, action):
        token = Token.objects.filter(token=token).first()
        if not token:
            self.msg = _(u"Error, token is invalid or expired")
            self.template_name = 'message.html'
        else:
            if action == 'unsubscribe':
                subs = Subscription.objects.get(token=token)
                subs.delete()
                self.msg = _(u"You subscription was deleted")
                self.template_name = 'message.html'
                return super(TokenAuth, self).get(request)
            post = ''
            path = ''
            for i in MODELS_FOR_EMAIL:
                post = getattr(token, i)
                path = MODELS_FOR_EMAIL[i]
                if post:
                    break
            user = token.user
            if user != request.user or not user.is_authenticated:
                user.is_authenticated = True
                user.backend = 'django.contrib.auth.backends.ModelBackend'
                login(self.request, user)
            if not user.is_verified():
                self.msg = _(u'Your email have been validated')
                user.emailaddress_set.filter(email=user.email).update(verified=True)
            if action == 'validate' or action == 'edit' or 'activate':
                post.is_active = True
                post.post_on_facebook()
                post.save()
                if action == 'edit':
                    return redirect(path, pk=post.id)
            elif action == 'delete':
                post.delete()
                self.msg = _(u"You post was deleted")
                self.template_name = 'message.html'
        return super(TokenAuth, self).get(request)

    def get_context_data(self, **kwargs):
        context = super(TokenAuth, self).get_context_data(**kwargs)
        if self.msg:
            context.update({'message': self.msg})
        return context


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = ['email', ]
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail")

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(email=self.request.user.email)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by email
    slug_field = "email"
    slug_url_kwarg = "email"

luxdjango/templates/pages/about.html
{% extends "base.html" %}

luxdjango/templates/pages/home.html
{% extends "base.html" %}
{% load pagination_tags staticfiles thumbnail %}
{% load staticfiles i18n %}

{% block content %}
    <!-- BEGIN: LAYOUT/SIDEBARS/QUICK-SIDEBAR -->
    <nav class="c-layout-quick-sidebar">
        <div class="c-header">
            <button type="button" class="c-link c-close">
                <i class="icon-login"></i>
            </button>
        </div>
    </nav>
    <!-- END: LAYOUT/SIDEBARS/QUICK-SIDEBAR -->
    <!-- BEGIN: PAGE CONTENT -->
    <!-- BEGIN: CONTENT/STATS/COUNTER-1 -->
    <div class="c-content-box c-size-md c-bg-white">
        <div class="container">
            <div class="c-content-counter-1 c-opt-1">
                <div class="c-content-title-1">
                    <h3 class="c-center c-font-uppercase c-font-bold">{% trans 'We never stop improving' %}</h3>
                    <div class="c-line-center"></div>
                </div>
                <div class="row">
                    <div class="col-sm-6 col-md-3">
                        <a class="c-counter c-theme-border c-font-bold c-theme-font"
                           href="{% url 'vehicles:all_vehicles' %}?sub_category=1"
                           data-counter="counterup">{{ vehicles_count }}</a>
                        <h4 class="c-title c-first c-font-uppercase c-font-bold"><a
                                href="{% url 'vehicles:all_vehicles' %}?sub_category=1">{% trans "Cars" %}</a></h4>
                    </div>
                    <div class="col-sm-6 col-md-3">
                        <a class="c-counter c-theme-border c-font-bold c-theme-font"
                           href="{% url 'realty:search' %}"
                           data-counter="counterup">{{ realty_count }}</a>
                        <h4 class="c-title c-font-uppercase c-font-bold"><a
                                href="{% url 'realty:search' %}">{% trans "Realty properties" %}</a></h4>
                    </div>
                    <div class="col-sm-6 col-md-3">
                        <a class="c-counter c-theme-border c-font-bold c-theme-font"
                           href="{% url 'jobs:search' %}"
                           data-counter="counterup">{{ jobs_count }}</a>
                        <h4 class="c-title c-font-uppercase c-font-bold"><a
                                href="{% url 'jobs:search' %}">{% trans "Jobs" %}</a></h4>
                    </div>
                     <div class="col-sm-6 col-md-3">
                        <a class="c-counter c-theme-border c-font-bold c-theme-font"
                           href="{% url 'classifieds:good_deals' %}"
                           data-counter="counterup">{{ classifieds_count }}</a>
                        <h4 class="c-title c-font-uppercase c-font-bold"><a
                                href="{% url 'classifieds:good_deals' %}">{% trans "Classifieds" %}</a></h4>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- END: CONTENT/STATS/COUNTER-1 -->
    <!-- BEGIN: CONTENT/TILES/TILE-3 -->
    <div class="c-content-box c-size-md c-bg-white">
        <div class="c-content-tile-grid c-bs-grid-reset-space">
            <div class="c-content-title-1 wow animate fadeInDown">
                <h3 class="c-font-uppercase c-center c-font-bold">{% trans 'New posts' %}</h3>
                <div class="c-line-center"></div>
            </div>
        </div>
        <div id="home-galary" class="container">
            <div class="row">
                <div class="c-content-box c-size-md c-bg-white">
                    {% for object in list_vehicles %}
                        <div class="col-md-3">
                            <a href="{% url 'vehicles:car-details' pk=object.id %}"
                               class="cbp-caption cbp-lightbox"
                               data-title="Seemple* Music for iPad<br>by Tiberiu Neamu">
                                <div class="cbp-caption-defaultWrap">
                                    {% thumbnail object.images.first.image "260x230" crop="center" as im %}
                                        <div class="c-bg-img-center c-overlay-object" data-height="height"
                                             style="height: 230px; background-image: url({{ im.url }});"></div>
                                        {% empty %}
                                        <div class="c-bg-img-center c-overlay-object" data-height="height"
                                             style="height: 230px; background-size:unset;
                                                     background-image: url({% static "assets/base/img/home.png" %});"></div>
                                    {% endthumbnail %}
                                    <div class="cbp-caption-activeWrap">
                                        <div class="cbp-l-caption-alignLeft">
                                            <div class="cbp-l-caption-body">
                                                <div class="cbp-l-caption-title"><span
                                                        id="car-brand">{{ object.brand.brand_name }}</span>
                                                    <span id="car-model">{{ object.model.model_name }}</span></div>
                                                <div class="cbp-l-caption-desc">{{ object.price }} &#8364;</div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                {% for object in list_realty %}
                    <div class="col-md-3">
                        <a href="{% url 'realty:details' pk=object.id %}"
                           class="cbp-caption cbp-lightbox"
                           data-title="Seemple* Music for iPad<br>by Tiberiu Neamu">
                            <div class="cbp-caption-defaultWrap">
                                {% thumbnail object.images.first.image "260x230" crop="center" as im %}
                                    <div class="c-bg-img-center c-overlay-object" data-height="height"
                                         style="height: 230px; background-image: url({{ im.url }});"></div>
                                    {% empty %}
                                    <div class="c-bg-img-center c-overlay-object" data-height="height"
                                         style="height: 230px; background-size:unset;
                                                 background-image: url({% static "assets/base/img/home.png" %});"></div>
                                {% endthumbnail %}
                                <div class="cbp-caption-activeWrap">
                                    <div class="cbp-l-caption-alignLeft">
                                        <div class="cbp-l-caption-body">
                                            <div class="cbp-l-caption-title">{{ object.get_deal_display }}
                                            {% if object.property_type_type.name %}
                                                {{ object.property_type_type.name }}
                                            {% else %}
                                                {{ object.property_type.name }}
                                            {% endif %}
                                                {{ object.city }}
                                            </div>
                                            <div class="cbp-l-caption-desc">
                                                {% if object.price %}{{ object.price }} &#8364; {% else %}<br>{% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- END: CONTENT/TILES/TILE-3 -->
    <!-- END: PAGE CONTENT -->
{% endblock content %}

{% block extra_js %}
    <script type="text/javascript">
    $(document).ready(function() {
        var searchInput = $('input[name="q"]');
        var overallSearchUrl = '{% url "overallsearch:search_ajax" %}';
        var countLinks = $('#search-counts a');
        var searching;

        searchInput.on('keyup', function(e) {
            e.preventDefault();
            if (searchInput.val().length > 2 && searchInput.val() != searching) {
                (function(v) {setTimeout(function() {
                    if (searchInput.val() === v) {
                        searching = v;
                        console.log('searching...', v);
                        $.ajax({
                            url :overallSearchUrl,
                            data: {q: v},
                            dataType: 'json',
                        }).done(function(response) {
                            for (var i = 0; i < countLinks.length; i ++) {
                                var link = $(countLinks[i]);
                                var key = link.data('key');
                                if (response.content[key]) {
                                    if (key !== 'notfound') {
                                        link.attr('href', addGETParam(link.attr('href'), 'q', v));
                                        link.find('.badge').text(response.content[key]);
                                    }
                                    link.css('display', 'block');
                                } else {
                                    link.hide();
                                }
                            }
                        });
                    }
                }, 500)})(searchInput.val());
            } else if (searchInput.val().length < 3) {
                countLinks.hide();
            }
        });

        function addGETParam(url, key, value) {
            value = encodeURIComponent(value);
            if (url.indexOf(key + '=') === -1) {
                if (url.indexOf('?') != -1) {
                    return url + '&' + key + '=' + value;
                } else {
                    return url + '?' + key + '=' + value;
                }
            } else {
                var m = url.match(/[?&]q=[^&]+/)[0];
                var ms = m.split('=');
                ms[1] = value;
                return url.replace(m, ms.join('='));
            }
        }

    });
    </script>
{% endblock extra_js %}